### ISSUE TITLE
cordova can't build the project

### ISSUE THREAD

**Issue by ehsand** [avivais/phonegap-parse-plugin#59]
cordova can't build the project with this plugin.
when i open the project in eclipse , eclipse shows error in  ParsePlugin.java
![error](https://cloud.githubusercontent.com/assets/1368996/7748113/ebada928-ffd6-11e4-975e-73525ff42794.jpg)

**Comment by kotamat** [comment]
you can get bolts-android.XXX.jar from Parse.zip
and copy it to platform/android/lib/

**Comment by ehsand** [comment]
thanks for your reply,
i do this and i get the apk,
 but now app get "force close" every time receives notification.

**Comment by budda** [comment]
@ehsand do you have the onCreate code set up as mentioned in the readme file about the Android quirks ?

**Comment by mobiRic** [comment]
What is Parse.zip? I was unable to find that file, but found the bolts-android jar file here:
- http://mvnrepository.com/artifact/com.parse.bolts/bolts-android/1.2.1

Anyone know how this can be fixed correctly, so that the plugin itself does that sort of copying?

I'm willing to put in some work to smooth out the issues, if I can ever get the lib working at all on Android.

**Comment by budda** [comment]
@mobiRic for my specific project I implemented a Cordova after_prepare hook to copy the file (and some other bits) into place for the android platform only.

**Comment by mobiRic** [comment]
@buddha good solution. 

Meantime I've switched to using a different plugin which already includes the bolts jar file automatically - I hope to suggest a pull request soon to this repo which copies the required files using the plugin.xml config file.

**Comment by mobiRic** [comment]
As you can see above, I have fixed this issue - pull request #73 pending.

@buddha you can hopefully do away with your after_prepare hook once this has been accepted.

**Comment by Montoya** [comment]
I just removed this plugin and installed the one from your git branch after running into the same issue. Unfortunately I still have the same issue. Not sure if I'm doing something wrong here but I'm going to try copying the file manually. 

I hope that your PR gets accepted but this plugin hasn't been maintained lately so who knows. If it doesn't maybe your branch will become the most popular one. Just in case, you should update your README.md so the install instruction points to your branch... currently it points to benjie's branch (not even avivais'!)

**Comment by mobiRic** [comment]
@Montoya strange that it isn't working - maybe that's why the PR has not been accepted. I will try make some time to confirm on my end.

As for my fork of this project, I only did that to create the PR in order to fix this project.

On my work I use a different plugin that does things in a way I am more familiar with.
